import argparse
import os
import shutil
import stat
import subprocess
import time
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE_ROOT = PROJECT_ROOT / "workspace"
DEMO_ROOT = WORKSPACE_ROOT / "demo_project"


README_CONTENT = """# Demo Project

这是 Mini Coding Agent Backend 的示例工作区项目。

CodeAgent 会在这个目录中进行文件读取、代码搜索、Git status、Git diff 和语法检查等演示任务。
"""


GITIGNORE_CONTENT = """# Generated by Mini Coding Agent
__pycache__/
*.pyc
*.pyo
*.bak
"""


BASELINE_MAIN_CONTENT = """from fastapi import FastAPI

app = FastAPI()


@app.get("/hello")
def hello():
    return {"message": "Hello, CodeAgent v1!"}
"""


WORKING_MAIN_CONTENT = """from fastapi import FastAPI

app = FastAPI()


@app.get("/hello")
def hello():
    return {"message": "Hello, Approval Agent!"}
"""


MATH_UTILS_CONTENT = '''def multiply(a, b):
    """返回 a 和 b 的乘积。"""
    return a * b
'''


UTILS_CONTENT = """def add(a, b):
    return a + b
"""


def handle_remove_readonly(func, path, exc_info):
    """
    Windows 下删除 .git 目录时，某些文件可能是只读的。
    这里先把文件改成可写，再重试删除。
    """
    try:
        os.chmod(path, stat.S_IWRITE)
        func(path)
    except Exception:
        raise


def remove_tree_safely(path: Path) -> bool:
    """
    更适合 Windows 的目录删除函数。

    解决：
    - .git/objects 文件只读
    - Windows 短暂文件占用
    - 删除失败后自动重试
    """
    for attempt in range(1, 4):
        try:
            shutil.rmtree(path, onexc=handle_remove_readonly)
            return True
        except PermissionError as e:
            print(f"⚠️  删除失败，可能文件被占用，正在重试 {attempt}/3")
            print(f"错误信息：{e}")
            time.sleep(1)

    print("❌ 删除 demo_project 失败。")
    print("请先关闭可能占用该目录的程序，例如 PyCharm 文件预览、Git Bash、终端、资源管理器窗口。")
    print(f"也可以手动删除目录：{path}")
    return False


def run_git(args: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        shell=False,
        check=False,
    )


def write_text(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def ensure_git_available() -> bool:
    result = subprocess.run(
        ["git", "--version"],
        capture_output=True,
        text=True,
        shell=False,
        check=False,
    )

    if result.returncode != 0:
        print("❌ 当前系统没有检测到 Git，请先安装 Git。")
        return False

    print(f"✅ 检测到 Git：{result.stdout.strip()}")
    return True


def has_git_commit(repo_path: Path) -> bool:
    result = run_git(["rev-parse", "--verify", "HEAD"], cwd=repo_path)
    return result.returncode == 0


def setup_demo_workspace(reset: bool):
    print("=" * 80)
    print("初始化 Demo Workspace")
    print("=" * 80)
    print(f"项目根目录：{PROJECT_ROOT}")
    print(f"Demo 目录：{DEMO_ROOT}")
    print()

    if not ensure_git_available():
        return 1

    if reset and DEMO_ROOT.exists():
        print("⚠️  --reset 已启用，正在删除旧的 demo_project...")

        if not remove_tree_safely(DEMO_ROOT):
            return 1

    WORKSPACE_ROOT.mkdir(parents=True, exist_ok=True)
    DEMO_ROOT.mkdir(parents=True, exist_ok=True)

    print("1. 写入 demo_project 基础文件")

    write_text(DEMO_ROOT / "README.md", README_CONTENT)
    write_text(DEMO_ROOT / ".gitignore", GITIGNORE_CONTENT)

    if not (DEMO_ROOT / ".git").exists():
        print("2. 初始化 demo_project Git 仓库")
        result = run_git(["init"], cwd=DEMO_ROOT)
        if result.returncode != 0:
            print("❌ git init 失败")
            print(result.stderr)
            return 1
    else:
        print("2. demo_project 已经是 Git 仓库")

    run_git(["config", "user.name", "Demo Agent"], cwd=DEMO_ROOT)
    run_git(["config", "user.email", "demo-agent@example.com"], cwd=DEMO_ROOT)

    if not has_git_commit(DEMO_ROOT):
        print("3. 创建 baseline commit")

        write_text(DEMO_ROOT / "main.py", BASELINE_MAIN_CONTENT)

        run_git(["add", "README.md", "main.py", ".gitignore"], cwd=DEMO_ROOT)
        result = run_git(["commit", "-m", "init demo project"], cwd=DEMO_ROOT)

        if result.returncode != 0:
            print("❌ git commit 失败")
            print(result.stderr)
            return 1
    else:
        print("3. baseline commit 已存在，跳过提交")

    print("4. 写入当前工作区示例文件")

    write_text(DEMO_ROOT / "main.py", WORKING_MAIN_CONTENT)
    write_text(DEMO_ROOT / "math_utils.py", MATH_UTILS_CONTENT)
    write_text(DEMO_ROOT / "utils.py", UTILS_CONTENT)

    print("5. 当前 demo_project Git 状态")
    result = run_git(["status", "--short"], cwd=DEMO_ROOT)

    if result.returncode == 0:
        print(result.stdout or "工作区干净")
    else:
        print("⚠️  Git status 获取失败")
        print(result.stderr)

    print("=" * 80)
    print("✅ Demo Workspace 初始化完成")
    print("=" * 80)

    return 0


def main():
    parser = argparse.ArgumentParser(
        description="初始化 Mini Coding Agent 的 demo_project 工作区"
    )

    parser.add_argument(
        "--reset",
        action="store_true",
        help="删除并重建 workspace/demo_project",
    )

    args = parser.parse_args()

    raise SystemExit(setup_demo_workspace(reset=args.reset))


if __name__ == "__main__":
    main()